services:
  #  app:
  #    image: muhsener98/urlshortener:0.0.1-SNAPSHOT
  #    container_name: my-urlshortener
  #    restart: always
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - db
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  redis_data:
  minio_data:

