spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: http://localhost:9000
  user: minioadmin
  password: minioadmin
  bucket-name: shortener


security:
  login-url: /api/v1/auth/login
  secret-key: asd9asdkJASD9ASUDASKDJASD0dslj
  token-expiration-time: 604800016
  token-prefix: "Bearer "




logging:
  level:
    demo.muhsener01: TRACE
    org.springframework.security: TRACE

application:
  properties:
    base-domain: http://localhost:5173
