spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MULTI_MAX_FILE_SIZE:5MB}
      max-request-size: ${MULTI_MAX_REQUEST_SIZE:10MB}
  datasource:
    hikari:
      connection-timeout: ${CONNECTION_TIMEOUT:5000}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shortener}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false


minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  user: ${MINIO_USER:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:shortenly}


security:
  login-url: /api/v1/auth/login
  secret-key: ${TOKEN_SECRET_KEY:12o38aSJKHASD8AS7DASKJH} #TODO: Delete default key.
  token-expiration-time: ${TOKEN_EXPIRATION_TIME:86400000}
  token-prefix: ${TOKEN_PREFIX:Bearer }


logging:
  level:
    demo.muhsener01: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}

application:
  properties:
    base-domain: ${BASE_URL:http://localhost:5173}
